copyright: Oliver Salzburg
dev_addr: 0.0.0.0:8000
docs_dir: docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oliversalzburg/
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  - search
repo_name: oliversalzburg/js-utils
repo_url: https://github.com/oliversalzburg/js-utils
site_name: JS Utils
theme:
  favicon: assets/images/favicon.ico
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: amber
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: indigo
      primary: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
